feat(glancevtkjsreader): import more volume properties from .vtkjs files
Kitware/paraview-glance pull request #384
Opened 2020-12-21 09:21 UTC by boucaud

2020-12-21 09:21 UTC, boucaud commented
@floryst @jourdain please review

2020-12-21 17:27 UTC, floryst requested changes

2020-12-21 17:27 UTC, floryst commented on src/io/GlanceVtkJsReader.js
> +            lutProxy.setMode(3);
Let's use the LookupTableProxy mode constant instead of a numerical constant. (See: https://github.com/Kitware/vtk-js/blob/master/Sources/Proxy/Core/LookupTableProxy/Constants.js)

2020-12-21 20:37 UTC, floryst approved these changes

2020-12-28 16:46 UTC, merged

2020-12-28 17:19 UTC, jourdain commented
:tada: This PR is included in version 4.14.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/paraview-glance/v/4.14.0)
- [GitHub release](https://github.com/Kitware/paraview-glance/releases/tag/v4.14.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: