Bump vtk-js
Kitware/paraview-glance pull request #394
Opened 2021-05-07 21:11 UTC by boucaud

This includes a small fix necessary for upgrade, because DataAccessHelpers now need to be explicitly registered, or imported.

2021-05-07 21:17 UTC, jourdain commented on src/io/GlanceVtkJsReader.js
> +import vtkJSZipDataAccessHelper from 'vtk.js/Sources/IO/Core/DataAccessHelper/JSZipDataAccessHelper';
You just need to import it so the `.get('zip')` will work. No need to do anything more.

2021-05-07 21:18 UTC, jourdain commented on src/io/GlanceVtkJsReader.js
> +import vtkJSZipDataAccessHelper from 'vtk.js/Sources/IO/Core/DataAccessHelper/JSZipDataAccessHelper';
Just add `import 'vtk.js/Sources/IO/Core/DataAccessHelper/JSZipDataAccessHelper';` at the top of the file

2021-05-07 21:24 UTC, jourdain commented on src/io/GlanceVtkJsReader.js
> +import vtkJSZipDataAccessHelper from 'vtk.js/Sources/IO/Core/DataAccessHelper/JSZipDataAccessHelper';
`import 'vtk.js/Sources/IO/Core/DataAccessHelper/JSZipDataAccessHelper';`

2021-05-07 21:24 UTC, jourdain commented on src/io/GlanceVtkJsReader.js
> +import vtkJSZipDataAccessHelper from 'vtk.js/Sources/IO/Core/DataAccessHelper/JSZipDataAccessHelper';
That way you don't need that comment for eslint

2021-05-07 21:28 UTC, boucaud commented on src/io/GlanceVtkJsReader.js
> +import vtkJSZipDataAccessHelper from 'vtk.js/Sources/IO/Core/DataAccessHelper/JSZipDataAccessHelper';
Thanks !

2021-05-10 14:32 UTC, floryst commented
Can you push the package-lock.json changes? It should be a fairly small change from what I can tell.

2021-05-10 14:34 UTC, floryst requested changes
Requesting changes so I know not to merge. Having package-lock.json committed helps in pinning a package version for CI.

2021-05-10 14:46 UTC, boucaud commented
> Can you push the package-lock.json changes? It should be a fairly small change from what I can tell.

done

2021-05-12 15:18 UTC, floryst commented
Thanks!

2021-05-12 15:18 UTC, merged

2021-05-12 15:23 UTC, jourdain commented
:tada: This PR is included in version 4.17.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/paraview-glance/v/4.17.1)
- [GitHub release](https://github.com/Kitware/paraview-glance/releases/tag/v4.17.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: